# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-24 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20160924_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='register_time',
        ),
    ]
