# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-26 00:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_remove_profile_register_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile',
            new_name='user',
        ),
    ]
