# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-26 00:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_auto_20160926_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=1, max_length=26),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='reg_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 26, 0, 35, 6, 122649, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
