# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-05 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_auto_20161005_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cuisines',
            field=models.CharField(max_length=300),
        ),
    ]
