# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-17 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0009_auto_20161008_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='zipcode',
            field=models.CharField(default='Not Available', max_length=20),
        ),
    ]
