# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-21 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0010_auto_20161017_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstation',
            name='Latitude',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='Longitude',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=15),
            preserve_default=False,
        ),
    ]
