# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-21 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0012_auto_20161021_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('HotelUrl', models.CharField(max_length=300)),
                ('City', models.CharField(max_length=300)),
                ('Address', models.CharField(max_length=300)),
                ('Latitude', models.DecimalField(decimal_places=82, max_digits=152)),
                ('Longitude', models.DecimalField(decimal_places=82, max_digits=152)),
            ],
        ),
    ]
