# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-22 03:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0015_remove_restaurant_country_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='Latitude',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='Longitude',
        ),
    ]
