# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-30 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0017_remove_hotel_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='Lock',
            field=models.BooleanField(default=False),
        ),
    ]
