# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-01 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0018_hotel_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstation',
            name='Lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='Lock',
            field=models.BooleanField(default=False),
        ),
    ]
